[package]
name = "gfx_sprite_2d"
version = "0.1.0"
authors = ["Justin Hamilton <justin@jamiltron.com>"]
license = "BSD-3-CLAUSE"
homepage = "https://github.com/jamiltron/gfx_sprite_2d"

[dependencies]
cgmath = "*"
gfx = "*"
gfx_window_glutin = "*"
glutin = "*"
image = "*"
